import type { Translation as DefaultTranslation } from '@shoelace-style/localize';
import { LocalizeController as DefaultLocalizationController } from '@shoelace-style/localize';
export declare class LocalizeController extends DefaultLocalizationController<Translation> {
}
export { registerTranslation } from '@shoelace-style/localize';
export interface Translation extends DefaultTranslation {
    $code: string;
    $name: string;
    $dir: 'ltr' | 'rtl';
    carousel: string;
    captions: string;
    clearEntry: string;
    close: string;
    createOption: (value: string) => string;
    copied: string;
    copy: string;
    currentValue: string;
    dropFileHere: string;
    decrement: string;
    dropFilesHere: string;
    enterFullscreen: string;
    error: string;
    exitFullscreen: string;
    goToSlide: (slide: number, count: number) => string;
    hidePassword: string;
    increment: string;
    loading: string;
    moreOptions: string;
    mute: string;
    nextSlide: string;
    nextVideo: string;
    numCharacters: (num: number) => string;
    numCharactersRemaining: (num: number) => string;
    numOptionsSelected: (num: number) => string;
    pause: string;
    pauseAnimation: string;
    pictureInPicture: string;
    play: string;
    playAnimation: string;
    playbackSpeed: string;
    playlist: string;
    previousSlide: string;
    previousVideo: string;
    progress: string;
    remove: string;
    resize: string;
    scrollableRegion: string;
    scrollToEnd: string;
    scrollToStart: string;
    selectAColorFromTheScreen: string;
    showPassword: string;
    slideNum: (slide: number) => string;
    toggleColorFormat: string;
    seek: string;
    seekProgress: (current: string, duration: string) => string;
    currentlyPlaying: string;
    unmute: string;
    videoPlayer: string;
    volume: string;
    zoomIn: string;
    zoomOut: string;
}
